### ISSUE TITLE
Issue with yarn install

### ISSUE THREAD

**Issue by RaviVaranasi** [siimon/prom-client#191]
Running `yarn install` after including `"prom-client": "^11.0.0"` to package.json causes error

```
ERROR in ./~/prom-client/lib/cluster.js
Module not found: Error: Can't resolve 'cluster' in '/Users/xxxxx/projects/xxxx/node_modules/prom-client/lib'
 @ ./~/prom-client/lib/cluster.js 11:16-34
 @ ./~/prom-client/index.js
 @ dll reactBoilerplateDeps
```

**Comment by SimenB** [comment]
`cluster` is a node core module (https://nodejs.org/api/cluster.html), `prom-client` does not support the browser

**Comment by RaviVaranasi** [comment]
Thanks. Appreciate the quick response.

**Comment by raulmmdev** [comment]
Hi @SimenB , i have a similar problem.
I'm trying to integrate prom-client with next js but i have the same problem.

`These dependencies were not found:

* cluster in ./node_modules/prom-client/lib/cluster.js
* fs in ./node_modules/prom-client/lib/metrics/processOpenFileDescriptors.js, ./node_modules/prom-client/lib/metrics/processMaxFileDescriptors.js and 1 other`

I do the const client = require("prom-client") on the getInitialProps that is on server side and the funny part is that if i do console.log(client) it works, but i get the error when compile.

I don't know if you can help me because the errors comes from prom-client or i need to open a issue on next js also.

Thanks for all

PS: This is how i know if client or server and is on server
`const isClientOrServer = () => {
  return typeof window !== "undefined" && window.document ? "client" : "server";
};`

**Comment by SimenB** [comment]
I think that's more of an issue for next.js. `prom-client` is strictly a node module and it needs to be ignored when building for the client

**Comment by raulmmdev** [comment]
Thanks for the quick response.
