### ISSUE TITLE
Using custom metrics

### ISSUE THREAD

**Issue by kentorio** [siimon/prom-client#206]
Probably just a question, however I couldn't get an answer via Stackoverflow as well and therefore I opened a bounty. I wasn't able to implement a custom metric and return it along with the default metrics as json.

```ts
import { Injectable } from '@nestjs/common';
import { collectDefaultMetrics, Counter, metric, Registry } from 'prom-client';

@Injectable()
export class PrometheusService {
  private register: Registry;
  private restRequestCounter: Counter;

  constructor() {
    this.register = new Registry();
    collectDefaultMetrics({ register: this.register });

    this.restRequestCounter = new Counter({
      name: 'incoming_rest_request_count',
      help: 'Number of all incoming http requests for this service'
    });
  }

  public incrementHttpRequestCount(): void {
    this.restRequestCounter.inc(1);
  }

  public getMetrics(): metric[] {
    return this.register.getMetricsAsJSON();
  }
}
```

Stackoverflow post: https://stackoverflow.com/questions/51431694/prometheus-client-doesnt-return-custom-metrics

**Comment by siimon** [comment]
The problem here is that you create your own custom registry and collect default metrics to that register, but with your counter you don't supply any register which means it will end up in the default one.

If you add the register to the counter it should work. Do you need your own custom registry? It's recommended to use the default one except certain use cases with for example modules.
