### ISSUE TITLE
Persisting prometheus client data with scalable application using Redis

### ISSUE THREAD

**Issue by bonzzy** [siimon/prom-client#207]
Is there a way to keep persisting `Prometheus` data across multiple Node instances? 
For example is there an easy way to connect `Redis` storage and persist data in there?

PHP client [Jimdo/prometheus_client_php](https://github.com/Jimdo/prometheus_client_php) has something like that implemented already.

**Comment by siimon** [comment]
Why would you want to do that? 

The reason why the PHP client does that is because of how PHP the language is designed and we don't have that problem in the node world.

**Comment by bonzzy** [comment]
What you said makes sense if you are working only with monolithic applications which are not scalable easily.
When you use `microservices` and you want to have a lot of instances of the application I think it is a good idea to be able to use `Redis` with Prometheus client.

My current example is large data streams, which must be balanced across multiple node instances.

**Comment by siimon** [comment]
Why can't each node be scraped by the Prometheus server?

**Comment by krukru** [comment]
Hey @siimon 

Think of this use case. You have a large cluster that you would like to monitor and expose metrics for prometheus. The cluster is too large to be monitored by one process, so you spawn a cluster of them. 

Each prom-client instance in this monitoring cluster is responsible for a fraction of the data in the entire cluster, this way the monitoring scales well.

But now you need a single entry-point for prometheus to scrape. This single entry-point needs to know about all other prom-client instances. 
For example, if you have 5 prom-client instances and each one increases a counter by 1, the result value on the counter should be 5, but you cannot get this without some shared memory.

But there is even a simpler use case for a shared persistent memory, what if for any reason your monitoring process crashes and restarts - when it boots up all it's metrics are reset to 0 - while in fact I would really like to just continue where things left off. 

While this does seem like a problem that is not within the scope of this library, php prometheus client has support for a arbitrary storage adapter and it is very helpful.

**Comment by siimon** [comment]
I think we got a different approach on how to monitor, for me, in a micro service world, each service exposes metrics through prom-client or any other metrics framework. There is no "monitoring cluster" on the client side, it's supposed to be as thin as possible. Each service can also have lots of instances, it doesn't matter since prometheus scrapes each single instance. 

Regarding your problem with metrics being reset to 0, that could be solved in other ways if it's important for you. One idea would be to push the metrics to a push gateway before process exits. 

And as you said, if it would be implemented, I think it belongs to a separate module and should not be included in prom-client, but instead having prom-client as a dependency.

**Comment by aequasi** [comment]
the different regions cannot be tracked/scraped. There is no way to know their IP or hostname. 

Push Gateways is not an avenue I'm willing to accept as a solution to my problem. It brings about too many other concerns that I don't want to deal with.

**Comment by siimon** [comment]
Then I am not sure Prometheus is the right tool for the job. What does the Prometheus core maintainers say about serverless?

**Comment by aequasi** [comment]
I don't understand why introducing a "Redis Registry" wouldn't continue to allow Prometheus being the right tool for the job.

**Comment by siimon** [comment]
Because it introduces a layer it wasn't designed for. Prometheus is designed for scraping the targets directly or through a push gateway (which is officially maintained). 

As I said, there is nothing stopping you to fork prom-client or use it as a dependency if you want to build it yourself but it won't be included in this project.

**Comment by grahamsutton** [comment]
@siimon Consider the following use case (which I'm actually going through right now):

I have a Remix.js application and a BullMQ worker. They share the same codebase but have separate builds. One build allows me to run the server the other allows me to run the worker.

The `/metrics` endpoint is exposed through the server. When I start the server, I initialize one registry. When I start the worker, this initializes a second separate registry because it runs in a separate process. When I observe metrics in my server, the metrics are visible at `/metrics`, but when I observe them in my worker, they are not (because again, separate process).

There's two ways that I see to get around this:

1. I configure an Express.js server for my BullMQ worker. (awkward and should be unnecessary)
2. Metrics share a centralized store (i.e. Redis/Memcached, etc)

There's also many benefits to centralizing the storage of metrics, primarily:

1. Exporting can be offloaded to other microservices (i.e. if you don't like your service getting spammed with requests to `/metrics` every 10 seconds but still need the frequency, you can spin up a separate Express.js server to handle the scraping on its behalf). 
2. Metrics don't need to be stored in Node.js memory. I've seen quite a few issues posted about memory limit problems. This would effectively solve all of them.
3. And of course, what I mentioned above already, which is that you can export metrics from across multiple processes.

The PHP counterpart library to this one [PromPHP/prometheus_client_php](https://github.com/PromPHP/prometheus_client_php) does this extremely well and actually makes Redis the default storage option, while still providing non-centralized storage alternatives like APCu.
