### ISSUE TITLE
metric.remove potentially broken

### ISSUE THREAD

**Issue by erdii** [siimon/prom-client#254]
First of all: Nice work! `prom-client` is my go-to prometheus exporter lib for node-based services! ❤

I think the `metric.remove` method added in #242 needs to be reworked because there is no safe way to hand over multiple label/value pairs. Or maybe I'm missing something.

Given a gauge metric, that I used to track this value:
```js
metric.set({
	first: "foo",
	second: "bar",
}, 1337)
```

I call `metric.remove("foo", "bar")` and I have to rely on js object-key ordering, which works in V8, but is not guaranteed in the language spec.

What I'd like to call is:
```js
metric.remove({
	first: "foo",
	second: "bar",
});
```

Edit: Formatting

**Comment by siimon** [comment]
PR welcome ☺️

**Comment by erdii** [comment]
@siimon assign me - I'll see what I can do :)

**Comment by erdii** [comment]
uh uh... i was not assigned and totally forgot about this one. will tackle it in the next weeks

**Comment by pepe79** [comment]
That bit me today. The remove function is also completely left out in the README.

**Comment by boris-chernysh** [comment]
> I call metric.remove("foo", "bar") and I have to rely on js object-key ordering, which works in V8, but is not guaranteed in the language spec.

When the delete method is called, an object is formed from labelNames and the passed values. So in fact, the call you make and the one you need are identical at some point.

The hash is calculated for key and valuBut I like the proposed interface because it is more consistent with the format when calling many methods and allows you to work with "holes" in labels.e pairs. When generating the hash, the keys are sorted by the built-in javascript sort method. the specification does not oblige it to be stable. So even if the interface changes, the problem remains :) 

But I like the proposed interface because it is more consistent with the format when calling many methods and allows you to work with "holes" in labels.

**Comment by alexey-sh** [comment]
is it resolved?

**Comment by erdii** [comment]
i guess so: https://github.com/siimon/prom-client/commit/3a86d05c49addc8294e9dcf16600226d6b970385

closing this
