### ISSUE TITLE
What is the default maxAge when using summary metric?

### ISSUE THREAD

**Issue by mahaben** [siimon/prom-client#296]
Memory keeps increasing in production day after day when using summary metric. I was wondering if specifying `maxAge` can solve the problem?

Here the code we use:

```
const periodicActionProcessingTimeMetric = new prometheusClient.Summary({
  name: 'periodic_action_processing_time_seconds',
  help: 'Periodic action processing time in seconds',
  labelNames: ['periodicActionId', 'processingSuccess'],
});
```

Thanks.

**Comment by zbjornson** [comment]
The default is no `maxAgeSeconds` or `ageBuckets`. Since #234 (see https://github.com/siimon/prom-client/pull/234#issuecomment-496120268 in particular) the values are compressed periodically (every 1000 observations by default), so there shouldn't be a leak (but might appear that way until you hit the compression point).

Setting both `maxAgeSeconds` and `ageBuckets` might reduce memory usage, but I'm not too familiar with these in practice. You could also try creating you Summary with a `compressCount` config parameter lower than 1000. That will use more CPU time but compress more frequently.
