### ISSUE TITLE
Tracking API of thirdparty

### ISSUE THREAD

**Issue by mituso89** [siimon/prom-client#332]
I want to tracking api of Thirdparty
For exs: Client -->Server-->API ThirdParty

At client -->server i was register metrics so i can't add new metrics at Server --> Third Party into list metrics at step client --> Server

How to monitoring API thirdparty. In a server call I need to sent 2-5 requests to a third party api. How to monitor it.

Any solution.

**Comment by siimon** [comment]
Not really sure about your question. 

Usually a node.js app runs as the server and then can make requests to other services and this where `prom-client` comes in as a way of adding metrics to the server. `prom-client` is not supported on running on the client side since that doesn't make sense since prometheus is a polling system.
