### ISSUE TITLE
report resolution of milliseconds

### ISSUE THREAD

**Issue by peynman** [siimon/prom-client#355]
Hi
How can i achieve milliseconds reporting, while Prometheus is asking for metrics each 1 seconds
`
const analogGuage = new client.Gauge({
        name: 'analog_read',
        help: 'Analog Read Value',
        labelNames: ["pin"]
    });
analogGuage.set({
                        pin: analog.i
                    }, analog.v);
`

related to this question: https://stackoverflow.com/questions/60848803/prometheus-and-node-exporter-in-milliseconds/60849173?noredirect=1#comment107668001_60849173

**Comment by sam-github** [comment]
Use a JS number, its floating point? `vInSecs = vInMsecs / 1000.0`?

**Comment by peynman** [comment]
analog.i and analog.v are both integers
I need my report timing to be in milliseconds, when I call function set on a guage, how to tell it the timestamp should be in millisecond and a new report will be generate a few millisec from now and Prometheus grab the metrics in few seconds...

**Comment by zbjornson** [comment]
I don't think Prometheus is the right tool for this scenario. Prometheus can't scrape that quickly (1s is probably the limit), and per #177 / #333 this library has no timestamp support because the only use case for timestamps is with custom collectors, which in turn this library doesn't support.

(That said, I'm not an expert in all the possible use cases of Prometheus. Maybe there's a way. The official go client library doesn't appear to have timestamp support either. I can't find a description of how timestamps are processed when they appear in the exposition.)

**Comment by peynman** [comment]
Yee. I have searched for days and I already saw #177 / #333, and asked myself why remove truly features like this :/  so may I ask, what is the resolution for default report tasks? I remember something like millisec support in them? how thats done!?

**Comment by zbjornson** [comment]
https://groups.google.com/forum/?nomobile=true#!topicsearchin/prometheus-users/timestamp;context-place=forum/prometheus-users/prometheus-users/1wJ8PUPG-8A/prometheus-users/1wJ8PUPG-8A might be useful (as might be other topics on timestamps in that group).

> what is the resolution for default report tasks?

I either don't understand what you're asking, or this isn't the right question. When Prometheus scrapes, it adds the current time to the metric values. Client libraries are supposed to expose the current values only. Internally I think the resolution is one millisecond.

I wish Prometheus supported collecting multiple timestamped values of the same metric as it definitely has use cases, but everything I can find says it's not built for that.

**Comment by zbjornson** [comment]
(post edited with working link)
