### ISSUE TITLE
process_cpu_seconds_total gauge breaks push gateway

### ISSUE THREAD

**Issue by tcolgate** [siimon/prom-client#37]
When trying to use prom-client with a long lived ETL batch job that needs to push, push gateway dies because prom-client uses a gauge for process_cpu_seconds_total (see prometheus/pushgateway#94)

process_cpu_seconds_total uses set on a gauge, but ideally should be exposed as a counter. Either prom-client to add set() to counter, or it should add reset(), then inc() the counter process_cpu_seconds_total counter.

**Comment by siimon** [comment]
Having a set function to the counter does not make any sense since it's not possible to decrease the value of the counter which is possible to do with a set function.

But as you are saying, the process_cpu_seconds_total metric has the wrong metric type, as the total in the metric name indicates as well. So my suggestion to fix this is to replace it from a Gauge to a Counter and just increment with the time spent - this is how the other official prometheus clients does it

**Comment by siimon** [comment]
Yeah, but what if the difference is negative? Then you'd need to decrease the counters value which is not allowed

**Comment by tcolgate** [comment]
The way process.cpuUsage() is being called. it should only ever go up anyway ( it could be called with the last value seen, and then you'll be able to inc().
