### ISSUE TITLE
Creating our own metrics

### ISSUE THREAD

**Issue by NicolasPelletier** [siimon/prom-client#72]
Good afternoon,

  I have a project in which we would like to create our own metrics and
we thought your library was interesting. We would like to base our code
on yours. Meaning we would like to inherit from yours or create new 
metrics with the same function signatures and styles.

  To do that, we would need access to some of the private content of
your library, such as the content of the `lib/utils.js` and
`lib/validation.js`.

  Would it be possible to make these functions public somehow ?

  Maybe you could export them this way:

```
  var defaultMetrics = require('./lib/defaultMetrics');
  defaultMetrics();

  module.exports = {
    // Main library
    register: require('./lib/register'),
    Counter: require('./lib/counter'),
    Gauge: require('./lib/gauge'),
    Histogram: require('./lib/histogram'),
    Summary: require('./lib/summary'),
    Pushgateway: require('./lib/pushgateway'),
    linearBuckets: require('./lib/bucketGenerators').linearBuckets,
    exponentialBuckets: require('./lib/bucketGenerators').exponentialBuckets,
    defaultMetrics: defaultMetrics,

    // To create your own metrics
    validateMetricName: require('./lib/validation').validateMetricName,
    validateLabelName: require('./lib/validation').validateLabelName,
    validateLabel: require('./lib/validation').validateLabel,

    getPropertiesFromObj: require('./lib/utils').getPropertiesFromObj,
    setValue: require('./lib/utils').setValue,
    getLabels: require('./lib/utils').getLabels,
    hashObject: require('./lib/utils').hashObject,
    isNumber: require('./lib/utils').isNumber,
  };
```

  What do you think ?

  Thanks,

  Nicolas Pelletier

**Comment by siimon** [comment]
I would prefer not to. This doesn't make sense to expose those private methods to the users of this module, it also makes it harder to do releases without major versions in case we would like to change something in utils or validations.

As I can see it you have 2 alternatives,

1. Fork this repo and maintain this fork by yourself (and then eventually fix breaking changes in your fork)

2. You could require the validation and until module today like require("prom-client/lib/until"), but this is quite dangerous since I can't guarantee this will work on newer versions of this lib!

**Comment by NicolasPelletier** [comment]
I quite understand your point of view here. Thanks for your prompt answer.
