### ISSUE TITLE
Including prom-client into Angular 2

### ISSUE THREAD

**Issue by homero304** [siimon/prom-client#77]
Is there an example available on how to load the library into an existing Angular2 project? Or is there a special configuration for this?

**Comment by siimon** [comment]
I've not done anything with angular but isn't that a client side framework? If not then just disregard from this!

Since Prometheus is pull based it doesn't make much sense to use it, even if you use the Pushgateway then it will need to be accessed publicly which brings a whole lot of other issues.

Maybe I misunderstood your question, then please clearify :)

**Comment by homero304** [comment]
No misunderstanding. You are right!
I need to monitor a UI Webpage for run-time errors. But since prometheus is pull based, it would not be a good idea (security reasons). Thanks, siimon
I appreciate the explanation you gave me.
I will check another approach to monitor the run-time errors.
